In [12]:
from sklearn.tree import DecisionTreeRegressor
from sklearn import datasets
import numpy as np
np.set_printoptions(precision=4, suppress=True, threshold=20)

In [13]:
# 加载只有两个特征的数据
boston = datasets.load_boston()  # Boston house prices dataset 波士顿房价预测
# 取2个特征  CRIM per capita crime rate by town  ;  人均犯罪率
# ZN proportion of residential land zoned for lots over 25,000 sq.ft. 占地25,000平方英尺以上的住宅用地比例
X = boston.data[:,0:2]
y = boston.target

In [14]:
X

array([[ 0.0063, 18.    ],
       [ 0.0273,  0.    ],
       [ 0.0273,  0.    ],
       ...,
       [ 0.0608,  0.    ],
       [ 0.1096,  0.    ],
       [ 0.0474,  0.    ]])

In [8]:
y

array([24. , 21.6, 34.7, ..., 23.9, 22. , 11.9])

决策树回归的工作方式类似于决策树分类，但不是减少基尼杂质或熵，而是测量潜在的分割点，它们减少均方误差（MSE）的程度:
$$MSE = \frac 1 n \sum_{i=1}^n (y_i - \hat y_i)^2$$
其中$y_i$是目标的真实值, $\hat y_i$是预测值

In [15]:
# 训练模型
dt_regr = DecisionTreeRegressor(random_state=12345)
dt_regr.fit(X, y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=12345, splitter='best')

In [16]:
# 新的观测点
observation = [[0.02, 16], [0.1, 0.2]]
dt_regr.predict(observation)

array([33. , 32.5])